# This rule is not used by the project platform-service-gitops itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to github.openmcp.cloud resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: platform-service-gitops
    app.kubernetes.io/managed-by: kustomize
  name: github-githubinstance-viewer-role
rules:
- apiGroups:
  - github.openmcp.cloud
  resources:
  - githubinstances
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - github.openmcp.cloud
  resources:
  - githubinstances/status
  verbs:
  - get
