apiVersion: gitops.open-control-plane.io/v1alpha1
kind: GitRepository
metadata:
  name: my-infra
  namespace: default
spec:
  url: https://github.com/my-org/my-infra
  ref:
    branch: main
  path: ./
  credentialRef:
    name: my-github-connection
    kind: AppInstallation
    group: github.gitops.open-control-plane.io
  propagateTo:
    - kind: ControlPlane
      name: my-mcp-prod
