name: E2E Tests

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  test-e2e:
    name: GitRepository propagateTo E2E
    runs-on: ubuntu-latest
    # Secrets live in the "e2e" environment for access control.
    environment: e2e
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Setup Go
        uses: actions/setup-go@4b73464bb391d4059bd26b0524d20df3927bd417 # v6.3.0
        with:
          go-version-file: go.mod
          cache: true

      - name: Build controller image
        run: make docker-build IMG=ghcr.io/openmcp-project/images/platform-service-gitops:$(./hack/common/get-version.sh)

      - name: Run E2E tests
        env:
          GITHUB_APP_ID: ${{ secrets.E2E_GITHUB_APP_ID }}
          GITHUB_APP_PRIVATE_KEY: ${{ secrets.E2E_GITHUB_APP_PRIVATE_KEY }}
          GITHUB_URL: ${{ secrets.E2E_GITHUB_URL }}
          GITHUB_ORG: ${{ secrets.E2E_GITHUB_ORG }}
          GITHUB_REPO_URL: ${{ secrets.E2E_GITHUB_REPO_URL }}
        run: |
          go mod tidy
          make test-e2e
